name: "linear-move-action"
description: Moves a linear list of issues from one state to another.

inputs:
  apiKey:
    description: Linear API Key
    required: true
  list:
    description: Linear list of attachement url or linear issues ids
    required: true
  from:
    description: Linear from state (If empty, will use any state)
    required: false
  to:
    description: Linear to state
    required: true

runs:
  using: "node16"
  main: "index.js"
