name: "linear-move-action"
description: Moves a linear list of issues from one state to another.

inputs:
  apiKey:
    description: Linear API Key (Required if accessToken is not provided)
    required: false
  accessToken:
    description: |
      Linear Access Token (Required if apiKey is not provided)
      Advised if you want to use a custom name for the bot, see https://developers.linear.app/docs/oauth/oauth-actor-authorization.
    required: false
  attachments:
    description: Linear list of attachement url (Separate with `separator`)
    required: false
  terms:
    description: Linear list of issue terms for search (Separate with `separator`)
    required: false
  separator:
    description: "Separator for attachments/terms as RegExp (Default: `\\s+`)"
    required: false
    default: "\\s+"
  from:
    description: Linear from state (If empty, will use any state) (Use `,` to separate mutliple states - any matching state will be used)
    required: false
  to:
    description: Linear to state (Use `,` to separate mutliple states - closest state will be used)
    required: true
  dry:
    description: Do not apply move
    required: false
    default: "false"

outputs:
  links:
    description: List of moved issues

runs:
  using: "node16"
  main: "index.js"
