name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: linear-move
        uses: nSimonFR/linear-move-action@main
        with:
          apiKey: ${{ secrets.LINEAR_API_KEY }}
          to: "In Progress, Review"
          attachments: https://example.com
          dry: true

      - if: steps.linear-move.outputs.links != 'https://linear.app/trusk/issue/PLA-32/test-linear-automation'
        run: exit 1
