name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: linear-move
        uses: nSimonFR/linear-move-action@main
        with:
          accessToken: ${{ secrets.LINEAR_ACCESS_TOKEN }}
          to: "In Progress, Review"
          attachments: https://example.com
          dry: true

      - if: contains(steps.linear-move.outputs.links, 'PLA-32') == false
        run: exit 1
