name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: attachments-test
        uses: nSimonFR/linear-move-action@main
        with:
          accessToken: ${{ secrets.LINEAR_ACCESS_TOKEN }}
          to: "In Progress, Review"
          attachments: https://example.com
          dry: true

      - if: contains(steps.attachments-test.outputs.links, 'PLA-32') == false
        run: exit 1

      - id: terms-test
        uses: nSimonFR/linear-move-action@main
        with:
          accessToken: ${{ secrets.LINEAR_ACCESS_TOKEN }}
          to: "In Progress, Review"
          terms: "TEST LINEAR AUTOMATION,anotherterm"
          separator: ","
          dry: true

      - if: contains(steps.terms-test.outputs.links, 'PLA-32') == false
        run: exit 1

      - id: urls-test
        uses: nSimonFR/linear-move-action@main
        with:
          accessToken: ${{ secrets.LINEAR_ACCESS_TOKEN }}
          to: "In Progress, Review"
          urls: "https://linear.app/trusk/issue/PLA-32"
          separator: ","
          dry: true

      - if: contains(steps.urls-test.outputs.links, 'PLA-32') == false
        run: exit 1
